### PR TITLE
[BACKPLANE-2015] Add backstage file

### PR DESCRIPTION
**Pull request by Nivl**
This PR adds Backstage to the repo.

### CODE REVIEW

**Review by tanya-coding — APPROVED** [review]
Left [question](https://circleci.slack.com/archives/C0F7E0EMQ/p1669676358849259) if we really need this but overall this LGTM. 

An even bigger question: should we go and retroactively update team's repos that use bond to add link? 😬

**Comment by Nivl** [comment]
> An even bigger question: should we go and retroactively update team's repos that use bond to add link? 😬

Looks like there are a couple of hundred of them 😰 . We'll need to figure something out.

**Comment by liamchzh** [comment]
> An even bigger question: should we go and retroactively update team's repos that use bond to add link? 😬

Probably not. Reasons are:
1. Many places need to be updated. And maintaining them would be hard.
2. Not sure if it makes sense to link libraries together.

**Review by liamchzh — APPROVED** [review]
Sorry, forgot to stamp this one.

**Pull request merged**
